[package]
name = "imgui-ggez-starter"
version = "0.1.0"
authors = ["oliviaifrim"]
edition = "2018"

[dependencies]
ggez = "0.5.1"

gfx_core = "0.9.2"
gfx_device_gl = "0.16.2"

imgui = "0.4"
imgui-gfx-renderer = "0.4"
