[package]
name = "imgui-ggez-starter"
version = "0.1.0"
authors = ["oliviaifrim"]
edition = "2018"

[dependencies]
ggez = "0.4.4"

gfx_core = "0.8.3"
gfx_device_gl = "0.15.3"

imgui = "0.0.22"
imgui-gfx-renderer = "0.0.22"
